# Generated by Django 2.1.5 on 2019-02-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataApp', '0007_merge_20190206_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='hockeyteam',
            name='team_logo',
            field=models.CharField(max_length=75, null=True),
        ),
    ]
