# Generated by Django 2.1.5 on 2019-02-09 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataApp', '0008_hockeyteam_team_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hockeyteam',
            name='team_logo',
        ),
    ]
